In [1]:
import statistics
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
beras = 11400
minyak = 12700
ayam = 3400
telur = 21800
popok = 27000
sabun = 1800
anggur = 3800
roti = 8500
tisue = 6400
mie = 2200
print("=== belanjaan tia ===")
beras_tia = 4
ayam_tia = 20
telur_tia = 3
sabun_tia = 5
anggur_tia = 4
roti_tia = 2
mie_tia = 12
jb_tia = (beras_tia * beras) + (ayam_tia * ayam) + (telur_tia * telur) + (sabun_tia * sabun) + (anggur_tia * anggur) + (roti_tia * roti) + (mie_tia * mie)
print("maka jumlah belanjaan tia " + str(jb_tia) +" rp")

print("=== belanjaan hana ===")
minyak_hana = 2
ayam_hana = 5
telur_hana = 1.5
sabun_hana = 3
anggur_hana = 8
roti_hana = 3
tisue_hana = 2
mie_hana = 20
jb_hana = (minyak_hana * minyak) + (ayam_hana * ayam) + (telur_hana * telur) + (sabun_hana * sabun) + (anggur_hana * anggur) + (roti_hana * roti) + (tisue_hana * tisue) + (mie_hana * mie)
print("maka jumlah belanjaan hana " + str(jb_hana) +" rp")

print("=== belanjaan widia===")
beras_widia = 1
minyak_widia = 1
telur_widia = 1
anggur_widia = 5
tisue_widia = 3
mie_widia = 16
jb_widia = (beras_widia * beras) + (minyak_widia * minyak) + (telur_widia * telur) + (anggur_widia * anggur) + (tisue_widia * tisue) + (mie_widia * mie)
print("maka jumlah belanjaan widia " + str(jb_widia) +" rp")
print("=== belanjaan samsul===")
ayam_samsul = 3
telur_samsul = 4
popok_samsul = 2
anggur_samsul = 7 
tisue_samsul = 5
mie_samsul = 10
jb_samsul = (ayam_samsul * (ayam * 10)) + (telur_samsul * telur) + (popok_samsul * popok) + (anggur_samsul * anggur) + (tisue_samsul * tisue) + (mie_samsul * mie)
print("maka jumlah belanjaan samsul " + str(jb_samsul) +" rp")
print("===belanjaan romi===")
minyak_romi = 3
telur_romi = 2
popok_romi = 4
sabun_romi = 8
mie_romi = 8
jb_romi = (minyak_romi * minyak) + (telur_romi * telur) + (popok_romi * popok) + (sabun_romi * sabun) + (mie_romi * mie)
print("maka jumlah belanjaan romi " + str(jb_romi) +" rp")
print("==belanjaan dimas===")
ayam_dimas = 5
popok_dimas = 5
sabun_dimas = 4
anggur_dimas = 3
roti_dimas = 5
mie_dimas = 6
jb_dimas =(ayam_dimas * (ayam * 10)) + (popok_dimas * popok) + (sabun_dimas * sabun) + (anggur_dimas * anggur) + (roti_dimas*roti) + (mie_dimas * mie)
print("maka jumlah belanjaan dimas " + str(jb_dimas) +" rp")
print("=== tiap tiap diskon ===")
diskon = 80
jb_diskon_tia = (jb_tia / 100) * diskon
print("maka jumlah belanjaan tia setelah mendapatkan diskon adalah " + str(jb_diskon_tia))
diskon = 85
jb_diskon_hana = (jb_hana / 100) * diskon
print("maka jumlah belanjaan widia setelah mendapatkan diskon adalah " + str(jb_diskon_hana))
diskon = 90
jb_diskon_widia = (jb_widia / 100) * diskon
print("maka jumlah belanjaan widia setelah mendapatkan diskon adalah " + str(jb_diskon_widia))
diskon = 75
jb_diskon_samsul = (jb_samsul / 100) * diskon
print("maka jumlah belanjaan samsul setelah mendapatkan diskon adalah " + str(jb_diskon_samsul))
diskon = 80
jb_diskon_romi = (jb_romi / 100) * diskon
print("maka jumlah belanjaan romi setelah mendapatkan diskon adalah " + str(jb_diskon_romi))
diskon = 75
jb_diskon_dimas = (jb_dimas / 100) * diskon
print("maka jumlah belanjaan dimas setelah mendapatkan diskon adalah " + str(jb_diskon_dimas))
print("=== soal 3 === ")
maxz = [284475]
print("maka jumlah belanjaan yang paling besar setelah diskon adalah dimas rp. " + str(maxz))

print("=== soal 4 ===")
tenpersen = {"hana" : "rp. 173880"}
print ("maka yang mendapatkan diskon 10persen adala : " + str(tenpersen))

=== belanjaan tia ===
maka jumlah belanjaan tia 246600 rp
=== belanjaan hana ===
maka jumlah belanjaan hana 193200.0 rp
=== belanjaan widia===
maka jumlah belanjaan widia 119300 rp
=== belanjaan samsul===
maka jumlah belanjaan samsul 323800 rp
===belanjaan romi===
maka jumlah belanjaan romi 221700 rp
==belanjaan dimas===
maka jumlah belanjaan dimas 379300 rp
=== tiap tiap diskon ===
maka jumlah belanjaan tia setelah mendapatkan diskon adalah 197280.0
maka jumlah belanjaan widia setelah mendapatkan diskon adalah 164220.0
maka jumlah belanjaan widia setelah mendapatkan diskon adalah 107370.0
maka jumlah belanjaan samsul setelah mendapatkan diskon adalah 242850.0
maka jumlah belanjaan romi setelah mendapatkan diskon adalah 177360.0
maka jumlah belanjaan dimas setelah mendapatkan diskon adalah 284475.0
=== soal 3 ===
maka jumlah belanjaan yang paling besar setelah diskon adalah dimas rp. [284475]
=== soal 4 ===
maka yang mendapatkan diskon 10persen adala : {'hana': 'rp. 173880'}